Repository caicloud/kubespray, pull requests merged in 2020-12, with the labels that each got.

#5 feat(*): Copy deploy-cluster config from sample templates
  .gitignore
  inventory/deploy-cluster/group_vars/all/all.yml
  inventory/deploy-cluster/group_vars/all/azure.yml
  inventory/deploy-cluster/group_vars/all/containerd.yml
  inventory/deploy-cluster/group_vars/all/docker.yml
  inventory/deploy-cluster/group_vars/all/oci.yml
  inventory/deploy-cluster/group_vars/etcd.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/addons.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-calico.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-canal.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-cilium.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-contiv.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-flannel.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-kube-router.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-macvlan.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-weave.yml
  inventory/deploy-cluster/inventory.ini
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note-none, size/XXL

#2 [CPS-705] feat(*): Infra package support Centos8.2 and containerd
  hack/infra/CentOS-8-All-In-One-local.repo
  hack/infra/install.sh
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/L

#3 [CPS-708] feat(*): Support install containerd server at alone host
  hack/infra/sources/CentOS-8-All-In-One.repo
  hack/infra/sources/infra_init.sh
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/L

#6 feat(*): Modify nginx default listen port
  .gitignore
  build/infra-nginx-image/Dockerfile
  build/infra-nginx-image/nginx.conf
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#8 feat(*): Set containerd and etcd version
  inventory/deploy-cluster/group_vars/all/all.yml
  roles/container-engine/containerd-common/vars/redhat.yml
  roles/download/defaults/main.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/XS

#9 feat(*): Add self-hosted module for containerOS
  cluster.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  roles/self-hosted/defaults/main.yml
  roles/self-hosted/tasks/main.yml
  roles/self-hosted/templates/cluster-config-info-cm.yml.j2
  roles/self-hosted/templates/cluster-crd-patch.yml.j2
  roles/self-hosted/templates/cluster-info-cm.yml.j2
  roles/self-hosted/templates/ssh_secret.yml.j2
  roles/self-hosted/templates/system-info-cm.yml.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/L

#10 feat(*): Support infra package source and cargo self-signed certificate
  inventory/deploy-cluster/group_vars/all/all.yml
  roles/bootstrap-os/tasks/bootstrap-centos.yml
  roles/bootstrap-os/tasks/main.yml
  roles/kubernetes/master/handlers/main.yml
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#11 fix(reset): fix reset problem
  roles/reset/tasks/main.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note-none, size/M

#12 feat(*): Add kubespray scripts
  run.sh
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/L

#7 feat(*): Modify kubespray default config
  inventory/deploy-cluster/group_vars/all/all.yml
  inventory/deploy-cluster/group_vars/etcd.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/addons.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-calico.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#14 fix(cluster.yml): Fix task judgment method
  cluster.yml
Labels: approved, area/release, caicloud-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#4 feat(networking): add network cni plugin
  cluster.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-calico.yml
  roles/kubernetes-apps/network_plugin/bd-multus/tasks/main.yml
  roles/kubernetes-apps/network_plugin/meta/main.yml
  roles/kubernetes/preinstall/tasks/0020-verify-settings.yml
  roles/network_plugin/bd-calico/defaults/main.yml
  roles/network_plugin/bd-calico/templates/calico-config.yml.j2
  roles/network_plugin/bd-calico/templates/calico-node.yml.j2
  roles/network_plugin/bd-calico/templates/cni-calico.conflist.j2
  roles/network_plugin/bd-calico/templates/kdd-crds.yml.j2
  roles/network_plugin/bd-multus/defaults/main.yml
  roles/network_plugin/bd-multus/files/multus-cm.yml
  roles/network_plugin/bd-multus/files/network-crd.yml
  roles/network_plugin/bd-multus/tasks/main.yml
  roles/network_plugin/bd-multus/templates/fixedip-ipam-server.yml.j2
  roles/network_plugin/bd-multus/templates/multus-daemonset.yml.j2
  roles/network_plugin/bd-multus/templates/network-agent-ds.yml.j2
  roles/network_plugin/bd-multus/templates/network-instances.yml.j2
  roles/network_plugin/meta/main.yml
  upgrade-cluster.yml
Labels: approved, caicloud-cla: yes, kind/api-change, kind/feature, lgtm, release-note, size/XL

#16 fix(*): fix network module status problem
  roles/download/defaults/main.yml
Labels: approved, area/release, caicloud-cla: yes, kind/bug, lgtm, release-note, size/XS

#17 feat(*): modify kube-proxy proxy mode configuration
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/XS

#18 feat(*): Add cos install.sh scripts
  config/env.yml
  config/inventory
  hack/cos/install.sh
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/L

#19 feat(*): modify registry auth in install scripts for push images
  hack/cos/install.sh
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/S

#21 fix(*): fix registry certificate check
  roles/bootstrap-os/tasks/bootstrap-centos.yml
Labels: approved, area/release, caicloud-cla: yes, kind/bug, lgtm, release-note, size/XS

#24 feat(*): Modify registry default project
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/S

#20 feat(*): Support upgrade registry secret
  roles/self-hosted/tasks/main.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/XS

#22 feat(*): Support user and password deploy cluster
  host-key.yml
  roles/self-hosted/defaults/main.yml
  roles/self-hosted/tasks/main.yml
  run.sh
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#29 feat(network): add network agent rbac
  roles/network_plugin/bd-multus/files/network-agent-rbac.yml
  roles/network_plugin/bd-multus/tasks/main.yml
  roles/network_plugin/bd-multus/templates/network-agent-ds.yml.j2
Labels: approved, area/network, caicloud-cla: yes, lgtm, release-note, size/M

#26 feat(network): set calico default vxlan backend
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-calico.yml
  roles/network_plugin/bd-calico/defaults/main.yml
  roles/network_plugin/bd-calico/templates/calico-node.yml.j2
  roles/network_plugin/bd-calico/templates/cni-calico.conflist.j2
Labels: approved, area/network, caicloud-cla: yes, kind/feature, lgtm, release-note, size/S

#30 feat(network): add fixedip-ipam rbac
  roles/network_plugin/bd-multus/files/fixedip-ipam-server-rbac.yml
  roles/network_plugin/bd-multus/tasks/main.yml
  roles/network_plugin/bd-multus/templates/fixedip-ipam-server.yml.j2
Labels: approved, area/network, caicloud-cla: yes, lgtm, release-note, size/M

#32 feat(network): update network crd
  roles/network_plugin/bd-multus/defaults/main.yml
  roles/network_plugin/bd-multus/files/network-crd.yml
  roles/network_plugin/bd-multus/templates/network-instances.yml.j2
Labels: approved, area/network, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#31 bugfix: adjust cluster-info cm networking
  roles/self-hosted/templates/cluster-info-cm.yml.j2
Labels: approved, area/network, caicloud-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#37 feat: add bd-calico reset
  roles/reset/tasks/main.yml
Labels: approved, area/network, caicloud-cla: yes, kind/feature, lgtm, release-note, size/XS

#33 fix: set correct type default value
  roles/network_plugin/bd-multus/templates/network-instances.yml.j2
Labels: approved, area/network, caicloud-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#35 feat(*): Add cluster vip to system-info configmap
  roles/self-hosted/templates/system-info-cm.yml.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/XS

#40 fix(*): Fix ssh key generate problem
  host-key.yml
  run.sh
Labels: approved, area/release, caicloud-cla: yes, kind/bug, lgtm, release-note, size/XS

#41 feat(*): Add labels in namespaces and configmap
  roles/self-hosted/tasks/main.yml
  roles/self-hosted/templates/cos-system-ns.yml.j2
  roles/self-hosted/templates/system-info-cm.yml.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#36 feat(*): Support Centos 7.9 and upgrade containerd version
  build/offline-source-nginx-image/Dockerfile
  build/offline-source-nginx-image/nginx.conf
  hack/infra/install.sh
  hack/offline-source/CentOS-7-All-In-One-local.repo
  hack/offline-source/CentOS-8-All-In-One-local.repo
  hack/offline-source/install.sh
  hack/offline-source/sources/CentOS-7-All-In-One.repo
  hack/offline-source/sources/CentOS-8-All-In-One.repo
  hack/offline-source/sources/infra_init.sh
  inventory/deploy-cluster/group_vars/all/all.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-calico.yml
  roles/bootstrap-os/tasks/bootstrap-centos.yml
  roles/container-engine/containerd-common/vars/redhat.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/L

#34 feat(*): optimization dockerfile
  build/cluster-deploy-job/Dockerfile
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/S

#28 feat(network): adjust CNI dir
  roles/container-engine/containerd/templates/config.toml.j2
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
  roles/network_plugin/bd-calico/handlers/main.yml
  roles/network_plugin/bd-calico/tasks/install.yml
  roles/network_plugin/bd-calico/templates/calico-node.yml.j2
  roles/network_plugin/bd-calico/templates/calicoctl.kdd.sh.j2
  roles/network_plugin/bd-calico/templates/cni-calico.conflist.j2
Labels: approved, area/network, caicloud-cla: yes, lgtm, release-note-none, size/S

#39 feat(*): Modify image repo, add download.yml file to group_vars/all directory.
  inventory/deploy-cluster/group_vars/all/all.yml
  inventory/deploy-cluster/group_vars/all/download.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/L

#42 feat(network): Calico upgrade
  inventory/deploy-cluster/group_vars/all/download.yml
  roles/network_plugin/bd-calico/templates/calico-node.yml.j2
  roles/network_plugin/bd-calico/templates/kdd-crds.yml.j2
Labels: approved, area/network, caicloud-cla: yes, kind/upgrade, lgtm, release-note, size/XXL

#44 fix(*): When firewalld is not installed, skip the disable operation
  roles/bootstrap-os/tasks/bootstrap-centos.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/XS

#38 feat(network): add calico backend options, support vxlan and bgp mode
  config/env.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-calico.yml
  roles/network_plugin/bd-calico/tasks/install.yml
  roles/network_plugin/bd-multus/templates/network-instances.yml.j2
Labels: approved, area/network, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#43 feat(network): upgrade network-agent
  inventory/deploy-cluster/group_vars/all/download.yml
  roles/network_plugin/bd-multus/templates/network-agent-ds.yml.j2
Labels: approved, area/network, caicloud-cla: yes, kind/upgrade, lgtm, release-note, size/XS

#48 feat(network): upgrade fixedip ipam version
  inventory/deploy-cluster/group_vars/all/download.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  roles/network_plugin/bd-multus/defaults/main.yml
  roles/network_plugin/bd-multus/files/fixedip-ipam-server-rbac.yml
  roles/network_plugin/bd-multus/templates/fixedip-ipam-server.yml.j2
Labels: approved, area/network, caicloud-cla: yes, kind/upgrade, lgtm, release-note, size/M

#49 fix(*): fix calicoctl binary checksums miss problem
  inventory/deploy-cluster/group_vars/all/download.yml
  roles/download/defaults/main.yml
Labels: approved, area/release, caicloud-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#45 fix(*): Fix the problem that self hosted directory does not exist
  roles/self-hosted/tasks/main.yml
Labels: approved, area/release, caicloud-cla: yes, kind/bug, lgtm, release-note, size/XS

#46 fix(*): Temporarily fix the problem of removing the cluster
  roles/reset/tasks/main.yml
Labels: approved, area/release, caicloud-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#51 chore(Dockerfile): update kubectl version to 1.19.3 and add .dockerignore
  .dockerignore
  build/cluster-deploy-job/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, size/S

#25 feat(*): Modify cluster config for cis
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/main.yml
  roles/kubernetes/master/templates/admission-control.yml.j2
  roles/kubernetes/master/templates/eventconfig.yml.j2
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#52 feat(network): add fixedip validating webhook
  roles/network_plugin/bd-multus/templates/fixedip-ipam-server.yml.j2
Labels: approved, area/network, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#53 fix(network): update fixedip validating webhook
  roles/network_plugin/bd-multus/templates/fixedip-ipam-server.yml.j2
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#50 fix(*): fix typo
  config/env.yml
  hack/cos/install.sh
  inventory/deploy-cluster/group_vars/all/all.yml
  inventory/deploy-cluster/group_vars/all/download.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  roles/bootstrap-os/tasks/bootstrap-centos.yml
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
  roles/self-hosted/defaults/main.yml
  roles/self-hosted/tasks/main.yml
  roles/self-hosted/templates/system-info-cm.yml.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note-none, size/M

#55 feat(network): set vxlan as default calico backend
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-calico.yml
Labels: approved, area/network, caicloud-cla: yes, kind/feature, lgtm, release-note, size/XS

#56 fix(network): service port needs name when it has multi ports
  roles/network_plugin/bd-multus/templates/fixedip-ipam-server.yml.j2
Labels: approved, area/network, caicloud-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#54 fix(run.sh): fix install scripts
  run.sh
Labels: approved, area/release, caicloud-cla: yes, kind/bug, lgtm, release-note-none, size/M

#57 feat(*): Support use skopeo sync image
  config/env.yml
  hack/k8s-installer/install.sh
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#59 feat(*): Modify configmap for controller deploy
  roles/self-hosted/templates/cluster-config-info-cm.yml.j2
  roles/self-hosted/templates/cluster-info-cm.yml.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/XS

#58 chore(install.sh): fix log output typo and image project typo
  hack/k8s-installer/install.sh
Labels: approved, caicloud-cla: yes, lgtm, size/S

#60 feat(*): Support gpu enhancement cluster
  config/env.yml
  inventory/deploy-cluster/group_vars/all/download.yml
  roles/self-hosted/templates/cluster-info-cm.yml.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/S

#66 feat(*): Add nvidia nouveau config
  roles/bootstrap-os/files/nvidia-nouveau.conf
  roles/bootstrap-os/tasks/bootstrap-centos.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/S

#65 fix(network): filled calico ds resources
  roles/network_plugin/bd-calico/templates/calico-node.yml.j2
Labels: approved, area/network, caicloud-cla: yes, kind/bug, lgtm, release-note-none, size/S

#64 feat(*): Add kubelet enhancement checksum
  roles/download/defaults/main.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/S

#63 feat(*): Add offline source container health check
  hack/offline-source/install.sh
  hack/offline-source/offline-source-health-check.sh
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/L

#61 feat(network): export default network params
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-calico.yml
  roles/network_plugin/bd-calico/defaults/main.yml
  roles/network_plugin/bd-calico/tasks/install.yml
  roles/network_plugin/bd-calico/templates/cni-calico.conflist.j2
  roles/network_plugin/bd-multus/defaults/main.yml
  roles/network_plugin/bd-multus/templates/network-instances.yml.j2
  roles/self-hosted/templates/cluster-info-cm.yml.j2
Labels: approved, area/network, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#67 fix(self-hosted): fix run once problem
  roles/self-hosted/tasks/main.yml
  run.sh
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#68 feat(*): Suport log self check
  run.sh
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/S

#72 fix: correct conf_dir of cri
  roles/container-engine/containerd/templates/config.toml.j2
  roles/network_plugin/bd-multus/files/multus-cm.yml
Labels: approved, area/network, caicloud-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#71 feat(*): Add cluster cidr to configmap
  roles/self-hosted/templates/cluster-config-info-cm.yml.j2
  roles/self-hosted/templates/cluster-info-cm.yml.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/S

#73 fix: remove calico interface when remove nodes
  roles/network_plugin/bd-calico/tasks/reset.yml
Labels: approved, area/network, caicloud-cla: yes, kind/bug, lgtm, release-note-none, size/M

#69 fix(*): Modify restart nginx pod command when add master node
  run.sh
Labels: approved, area/release, caicloud-cla: yes, kind/bug, lgtm, release-note, size/XS

#70 feat(*): Patch kubeconfig file to cluster crd
  roles/self-hosted/tasks/main.yml
  roles/self-hosted/templates/cluster-crd-patch.yml.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#76 fix: ensure calico cni dir
  roles/kubernetes/preinstall/tasks/0050-create_directories.yml
Labels: approved, area/network, caicloud-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#78 fix: use release_image_repo for self-developed images
  inventory/deploy-cluster/group_vars/all/download.yml
Labels: approved, area/network, caicloud-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#77 fix: upgrade multus to an internal version v3.6.2-rc.1
  inventory/deploy-cluster/group_vars/all/download.yml
Labels: approved, area/network, caicloud-cla: yes, lgtm, release-note, size/XS
