Repository caicloud/kubespray, pull requests merged in 2021-01, with the labels that each got.

#75 feat(*): Modify kernel config
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#87 feat(*): add convert-images command for generate images list
  Makefile
  inventory/deploy-cluster/group_vars/all/download.yml
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#81 feat: change some net sysctl
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
Labels: approved, caicloud-cla: yes, kind/feature, lgtm, release-note-none, size/S

#86 fix: optimizer calico reset
  roles/network_plugin/bd-calico/tasks/reset.yml
  roles/reset/tasks/main.yml
Labels: approved, area/network, caicloud-cla: yes, lgtm, release-note-none, size/XS

#88 fix: change multus image name to 'multus-cni'
  inventory/deploy-cluster/group_vars/all/download.yml
Labels: approved, area/network, caicloud-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#79 feat(*): Add etcd tls secret to cluster
  roles/self-hosted/defaults/main.yml
  roles/self-hosted/tasks/main.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/S

#80 feat(*): Support monitoring needs
  inventory/deploy-cluster/group_vars/all/containerd.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#84 feat(*): Modify cluster-config-info configmap
  roles/self-hosted/templates/cluster-config-info-cm.yml.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note-none, size/XS

#90 fix: remove net bridge sysctl
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
Labels: approved, area/network, caicloud-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#82 feat(*): Use logrotate as log tool for containerd and kubelet services
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  roles/container-engine/containerd/tasks/containerd_logrotate.yml
  roles/container-engine/containerd/tasks/main.yml
  roles/container-engine/containerd/templates/containerd-logrotate.j2
  roles/container-engine/containerd/templates/containerd-service.j2
  roles/etcd/tasks/configure.yml
  roles/etcd/templates/etcd-events-host-logrotate.j2
  roles/etcd/templates/etcd-host-logrotate.j2
  roles/kubernetes/node/tasks/kubelet.yml
  roles/kubernetes/node/templates/kubelet-logrotate.j2
  roles/kubernetes/node/templates/kubelet.service.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/L

#89 chore(*): optimize cluster-deploy-job image build
  Makefile
  build/cluster-deploy-job/Dockerfile
  build/kubespray-base-image/Dockerfile
  hack/lint/lint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/L

#83 feat: update fixedip ipam
  inventory/deploy-cluster/group_vars/all/download.yml
  roles/network_plugin/bd-multus/files/fixedip-ipam-server-rbac.yml
  roles/network_plugin/bd-multus/templates/fixedip-ipam-server.yml.j2
Labels: approved, area/network, caicloud-cla: yes, kind/upgrade, lgtm, release-note-none, size/M

#92 feat: upgrade network agent version
  inventory/deploy-cluster/group_vars/all/download.yml
Labels: approved, area/network, caicloud-cla: yes, kind/upgrade, lgtm, release-note, size/XS

#93 feat(networking): update multus daemonset for fixedip client
  roles/network_plugin/bd-multus/templates/multus-daemonset.yml.j2
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#74 feat(*): Support create cluster vip in user cluster
  Makefile
  build/keepalived/Dockerfile
  hack/k8s-installer/install.sh
  inventory/deploy-cluster/group_vars/all/download.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/self-hosted/defaults/main.yml
  roles/self-hosted/tasks/create-vip.yml
  roles/self-hosted/tasks/main.yml
  roles/self-hosted/templates/cluster-vip-cm.yml.j2
  roles/self-hosted/templates/cluster-vip-daemonset.yml.j2
  roles/self-hosted/templates/cluster-vip-rbac.yml.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/L

#94 feat: cleanup network-agent rules
  roles/reset/tasks/main.yml
Labels: approved, area/network, caicloud-cla: yes, kind/feature, lgtm, release-note, size/XS

#91 feat(*): Add full resources config for kubernetes components
  inventory/deploy-cluster/group_vars/all/download.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/main.yml
  roles/kubernetes/master/tasks/resources-config.yml
  roles/kubernetes/master/templates/resources/kube-apiserver-resources.yaml.j2
  roles/kubernetes/master/templates/resources/kube-controller-manager-resources.yaml.j2
  roles/kubernetes/master/templates/resources/kube-scheduler-resources.yaml.j2
  roles/kubernetes/node/templates/manifests/nginx-proxy.manifest.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/L

#95 fix(*): Fix errors in deployment scripts and makefile files
  Makefile
  hack/k8s-installer/install.sh
Labels: approved, area/release, caicloud-cla: yes, kind/bug, lgtm, release-note-none, size/XS

#97 feat(*): update fixedip ipam config cni-calico
  roles/network_plugin/bd-calico/defaults/main.yml
  roles/network_plugin/bd-calico/templates/cni-calico.conflist.j2
Labels: approved, area/network, caicloud-cla: yes, kind/feature, lgtm, release-note, size/XS

#96 feat(Jenkinsfile): auto package for kubespray
  Makefile
  hack/auto-release/Jenkinsfile
  hack/auto-release/check.py
  hack/auto-release/sync.sh
  images-lists/images_kubernetes.list
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XL

#100 chore(Jenkinsfile): fix KUBESPRAY_BRANCH and PACKAGE_NAME typo
  hack/auto-release/Jenkinsfile
Labels: approved, lgtm, release-note-none, size/M

#98 feat(*): Modify cluster cidr and service cidr
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/XS

#99 feat(*): Add etcd service logrotate config
  roles/etcd/templates/etcd-events-host.service.j2
  roles/etcd/templates/etcd-host.service.j2
Labels: approved, area/release, caicloud-cla: yes, kind/feature, lgtm, release-note, size/XS

#101 feat(*): Upgrade kubernetes version to v1.19.6
  README.md
  config/env.yml
  config/inventory
  images-lists/images_kubernetes.list
  inventory/deploy-cluster/group_vars/all/download.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  roles/download/defaults/main.yml
  roles/kubernetes/master/tasks/resources-config.yml
  roles/kubespray-defaults/defaults/main.yaml
Labels: approved, area/release, kind/feature, kind/upgrade, lgtm, release-note, size/L

#103 chore(build): update kubectl version in dockerfile
  Makefile
  build/kubespray-base-image/Dockerfile
Labels: approved, lgtm, release-note, size/XS

#102 feat(*): Add ungzip image file in deploy scripts
  hack/k8s-installer/install.sh
Labels: approved, area/release, kind/feature, lgtm, release-note, size/XS

#104 chore(install.sh): adjust the execution path by auto package
  hack/auto-release/Jenkinsfile
  hack/k8s-installer/install.sh
Labels: approved, lgtm, release-note-none, size/S

#105 chore(sync.sh): copy sync image script form product-release
  hack/auto-release/Jenkinsfile
  hack/auto-release/sync.sh
Labels: approved, lgtm, release-note-none, size/S

#106 chore(Jenkinsfile): fix ssh_cert path name typo
  hack/auto-release/Jenkinsfile
Labels: approved, lgtm, release-note-none, size/XS

#107 feat(*): Modify deploy scripts and psp config
  hack/offline-source/install.sh
  inventory/deploy-cluster/group_vars/k8s-cluster/psp-config.yml
  run.sh
Labels: approved, area/release, kind/feature, lgtm, release-note, size/M

#108 feat(*): Support platform config
  inventory/deploy-cluster/group_vars/all/all.yml
  roles/kubernetes/preinstall/tasks/0200-platform_requirements.yml
  roles/kubernetes/preinstall/tasks/main.yml
  roles/kubernetes/preinstall/vars/centos.yml
  roles/self-hosted/tasks/main.yml
Labels: approved, area/release, kind/feature, lgtm, release-note, size/M

#110 feat(*): Add cluater deploy job image version to system-info configmap
  hack/k8s-installer/install.sh
  inventory/deploy-cluster/group_vars/all/all.yml
  roles/self-hosted/defaults/main.yml
  roles/self-hosted/templates/system-info-cm.yml.j2
  run.sh
Labels: approved, area/release, kind/feature, lgtm, release-note, size/S

#109 feat(*): Add kube-proxy resource config
  roles/kubernetes/master/defaults/main/main.yml
  roles/kubernetes/master/tasks/resources-config.yml
  roles/kubernetes/master/templates/resources/kube-proxy-daemonset.yaml.j2
Labels: approved, area/release, kind/feature, lgtm, release-note, size/M

#112 fix(network): parse value to boolean
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  roles/network_plugin/bd-calico/templates/cni-calico.conflist.j2
Labels: approved, area/network, kind/bug, lgtm, release-note-none, size/XS

#113 feat(*): Remove kernel nouveau module
  roles/bootstrap-os/tasks/bootstrap-centos.yml
Labels: approved, area/release, kind/feature, lgtm, release-note, size/S

#114 feat(*): Fix remove node error
  run.sh
Labels: approved, area/release, kind/bug, lgtm, release-note-none, size/XS

#111 fix(*): Fix the unreasonable writing of variable judgment
  roles/bootstrap-os/tasks/bootstrap-centos.yml
  roles/kubernetes/preinstall/tasks/0200-platform_requirements.yml
  roles/self-hosted/tasks/main.yml
Labels: approved, area/release, kind/bug, lgtm, release-note-none, size/S

#115 feat(*): Remove kubelet rotate server certificates
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  roles/self-hosted/tasks/main.yml
Labels: approved, area/release, kind/feature, lgtm, release-note-none, size/XS

#116 feat(*): Increase taint tolerance and create label on master node
  roles/self-hosted/tasks/main.yml
  roles/self-hosted/templates/cluster-vip-daemonset.yml.j2
Labels: approved, area/release, kind/feature, lgtm, release-note, size/M

#118 fix(network): parse recycle_enabled to boolean
  roles/network_plugin/bd-multus/templates/network-instances.yml.j2
Labels: approved, area/network, kind/bug, lgtm, release-note-none, size/XS

#117 fix(network): calico bgp config
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-net-calico.yml
  roles/network_plugin/bd-calico/templates/calico-config.yml.j2
Labels: approved, area/network, kind/bug, lgtm, release-note-none, size/XS

#121 fix(*): Fix error when containerd is not installed
  roles/reset/tasks/main.yml
Labels: approved, area/release, kind/bug, lgtm, release-note, size/XS

#120 feat(*): Modify sysctl config
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
Labels: approved, area/network, area/release, kind/feature, lgtm, release-note, size/S

#119 feat(*): Add time synchronization function
  config/env.yml
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
  roles/kubernetes/preinstall/templates/chrony.conf.j2
  roles/kubernetes/preinstall/vars/centos.yml
  roles/self-hosted/templates/system-info-cm.yml.j2
Labels: approved, area/release, kind/feature, lgtm, release-note, size/L

#123 fix(*): Modify the Boolean value judgment method
  cluster.yml
  inventory/deploy-cluster/group_vars/all/download.yml
  roles/kubernetes/preinstall/tasks/0200-platform_requirements.yml
  roles/kubernetes/preinstall/tasks/main.yml
Labels: approved, area/release, kind/feature, lgtm, release-note-none, size/XS

#122 feat(*): Support non-root users to deploy clusters
  ansible.cfg
Labels: approved, area/release, kind/feature, lgtm, release-note, size/XS

#124 feat(*): Install glusterfs client by default
  hack/offline-source/CentOS-7-All-In-One-local.repo
  hack/offline-source/sources/CentOS-7-All-In-One.repo
  inventory/deploy-cluster/group_vars/all/all.yml
Labels: approved, area/release, kind/feature, lgtm, release-note, size/S

#127 feat(*): Allow independent deployment of etcd nodes
  cluster.yml
  roles/self-hosted/tasks/main.yml
Labels: approved, area/release, kind/feature, lgtm, release-note, size/M

#125 feat(*): Increase the use of containeros requires an installation package
  hack/offline-source/CentOS-7-All-In-One-local.repo
  hack/offline-source/sources/CentOS-7-All-In-One.repo
  roles/kubernetes/preinstall/vars/centos.yml
Labels: approved, area/release, kind/feature, lgtm, release-note, size/M

#128 fix(*): Fix gluster client install problem
  inventory/deploy-cluster/group_vars/all/all.yml
  roles/kubernetes/preinstall/vars/centos.yml
Labels: approved, area/release, kind/bug, lgtm, release-note-none, size/XS

#126 feat: adjust ingress version to networking v1
  inventory/deploy-cluster/group_vars/k8s-cluster/k8s-cluster.yml
Labels: approved, area/network, kind/feature, lgtm, release-note, size/XS

#130 chores: make container name clear
  roles/network_plugin/bd-multus/templates/fixedip-ipam-server.yml.j2
  roles/network_plugin/bd-multus/templates/network-agent-ds.yml.j2
Labels: approved, lgtm, release-note-none, size/XS

#132 feat(): fixedip log level
  roles/network_plugin/bd-multus/templates/fixedip-ipam-server.yml.j2
Labels: approved, area/network, kind/feature, lgtm, release-note, size/XS

#131 fix: remove blackhole route when remove node
  roles/network_plugin/bd-calico/tasks/reset.yml
Labels: approved, area/network, kind/bug, lgtm, release-note-none, size/XS

#133 feat(*): fixedip network-agent version
  inventory/deploy-cluster/group_vars/all/download.yml
Labels: approved, area/network, kind/feature, lgtm, release-note, size/XS

#129 feat(hack): add inventory.sh for generate inventory by input parameters
  .gitignore
  hack/k8s-installer/tools/inventory.sh
Labels: approved, lgtm, release-note, size/M

#134 feat(*): Modify k8s-installer deploy scripts
  hack/k8s-installer/install.sh
Labels: approved, area/release, kind/feature, lgtm, release-note, size/M

#135 feat(*): update kubelet 1.19.6 enhancement checksums
  roles/download/defaults/main.yml
Labels: approved, area/release, kind/upgrade, lgtm, release-note, size/XS

#137 chore(Jenkinsfile): copy k8s-installer/tools to install package
  hack/auto-release/Jenkinsfile
Labels: approved, lgtm, release-note-none, size/XS

#139 feat(*): Modify sysctl config
  roles/kubernetes/preinstall/tasks/0080-system-configurations.yml
Labels: approved, area/release, kind/feature, lgtm, release-note-none, size/XS

#141 feat(*): Modify containerd version for ubuntu and debian system
  roles/container-engine/containerd-common/vars/debian.yml
  roles/container-engine/containerd-common/vars/ubuntu-amd64.yml
Labels: approved, area/release, kind/feature, lgtm, release-note, size/S

#138 feat(*): Modify offline source log file
  hack/offline-source/install.sh
  hack/offline-source/offline-source-health-check.sh
Labels: approved, area/release, kind/feature, lgtm, release-note, size/S

#143 feat(*): Modify scripts for volume deploy
  hack/k8s-installer/install.sh
Labels: approved, area/release, kind/feature, lgtm, release-note-none, size/S

#140 fix(*): service unavailable when pod use bridge-vlan
  roles/kubernetes/master/templates/kubeadm-config.v1beta2.yaml.j2
Labels: approved, area/network, kind/bug, lgtm, release-note, size/XS

#145 feat(*): Support configuration files for different environments
  config/cos/env.yml
  config/cos/inventory
  config/storage/env.yml
  config/storage/inventory
Labels: approved, area/release, do-not-merge/hold, kind/feature, lgtm, release-note, size/L

#142 fix(*): Fix cluster vip config
  roles/self-hosted/defaults/main.yml
  roles/self-hosted/tasks/create-vip.yml
  roles/self-hosted/templates/cluster-vip-cm.yml.j2
  roles/self-hosted/templates/cluster-vip-daemonset.yml.j2
Labels: approved, area/release, kind/bug, lgtm, release-note, size/S

#144 fix(*): Set shell command timeout
  roles/bootstrap-os/tasks/bootstrap-centos.yml
  roles/kubernetes/preinstall/defaults/main.yml
  roles/kubernetes/preinstall/tasks/0090-etchosts.yml
Labels: approved, area/release, kind/bug, lgtm, release-note, size/S

#146 feat(*): Support non-containeros environment deployment
  hack/k8s-installer/install.sh
Labels: approved, area/release, kind/feature, lgtm, release-note-none, size/S

#147 feat(*): update fixedip version
  images-lists/images_kubernetes.list
  inventory/deploy-cluster/group_vars/all/download.yml
Labels: approved, area/network, kind/upgrade, lgtm, release-note, size/XS
